services:
  - type: web
    name: NEZUKO-MD
    env: node
    branch: main
    repo: https://github.com/Godzenox00/NEZUKO-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ğš€ğšğšğšğš—-ğ™½ğšğš£ğšğš”ğš˜;ğš‰ğšğš—ğš˜ğš¡;https://ik.imagekit.io/Oggy/FgmTXI_3JCrg1fN9.jpg
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: ğš‰ğ™´ğ™½ğ™¾ğš‡;ğ™½ğ™´ğš‰ğš„ğ™ºğ™¾;https://ik.imagekit.io/Oggy/FgmTXI_3JCrg1fN9.jpg
      - key: PREFIX
        value: ^
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: ğğ„ğ™ğ”ğŠğ ğŒğƒğŸŒˆ
      - key: STICKER_DATA
        value: Zenox;nezuko
      - key: SUDO
        value: 9197441089700
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true
